blueprint:
  name: Office Fan with Temperature and Door (°F)
  description: |
    Turns on fan if inside temp > high threshold and outside temp ≤ inside temp.
    Turns off if inside temp < low threshold.
    Temporarily turns off fan when door opens; turns back on when door closes only if conditions are still met.
    All temperatures in Fahrenheit.
  domain: automation
  input:
    fan_switch:
      name: Fan Switch
      selector:
        entity:
          domain: switch
    inside_temp:
      name: Inside Temperature Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
    outside_temp:
      name: Outside Temperature Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
    door_sensor:
      name: Door Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: opening
    high_threshold:
      name: High Threshold (turn fan ON above)
      description: Inside temperature in °F
      default: 77
      selector:
        number:
          min: 32
          max: 120
          step: 0.5
          unit_of_measurement: °F
          mode: box
    low_threshold:
      name: Low Threshold (turn fan OFF below)
      description: Inside temperature in °F
      default: 70
      selector:
        number:
          min: 32
          max: 120
          step: 0.5
          unit_of_measurement: °F
          mode: box

trigger:
  - platform: state
    entity_id:
      - !input inside_temp
      - !input outside_temp
    id: temp_change
  - platform: state
    entity_id: !input door_sensor
    from: "off"
    to: "on"
    id: door_open
  - platform: state
    entity_id: !input door_sensor
    from: "on"
    to: "off"
    id: door_close

mode: queued
max_exceeded: silent

action:
  - variables:
      inside_temp_id: !input inside_temp
      outside_temp_id: !input outside_temp
  - choose:
      # Temperature changed
      - conditions:
          - condition: trigger
            id: temp_change
        sequence:
          # Turn ON if inside > high AND outside ≤ inside AND fan currently off
          - if:
              - condition: numeric_state
                entity_id: !input inside_temp
                above: !input high_threshold
              - condition: template
                value_template: >-
                  {{ states(outside_temp_id) | float(-999) <= states(inside_temp_id) | float(-999) }}
              - condition: state
                entity_id: !input fan_switch
                state: "off"
            then:
              - service: switch.turn_on
                target:
                  entity_id: !input fan_switch

          # Turn OFF if inside < low AND fan currently on
          - if:
              - condition: numeric_state
                entity_id: !input inside_temp
                below: !input low_threshold
              - condition: state
                entity_id: !input fan_switch
                state: "on"
            then:
              - service: switch.turn_off
                target:
                  entity_id: !input fan_switch

      # Door opened → force fan off
      - conditions:
          - condition: trigger
            id: door_open
        sequence:
          - if:
              - condition: state
                entity_id: !input fan_switch
                state: "on"
            then:
              - service: switch.turn_off
                target:
                  entity_id: !input fan_switch

      # Door closed → turn fan back on only if conditions still met
      - conditions:
          - condition: trigger
            id: door_close
        sequence:
          - if:
              - condition: numeric_state
                entity_id: !input inside_temp
                above: !input high_threshold
              - condition: template
                value_template: >-
                  {{ states(outside_temp_id) | float(-999) <= states(inside_temp_id) | float(-999) }}
              - condition: state
                entity_id: !input fan_switch
                state: "off"
            then:
              - service: switch.turn_on
                target:
                  entity_id: !input fan_switch
