blueprint:
  name: Office Lights with Presence and Motion (mmWave fix)
  description: >-
    Turns lights on when motion, mmWave occupancy, or door opens. Keeps lights on while presence/occupancy is detected.
    Uses a timer to turn off after configurable delay when presence is gone.
    Door only triggers ON, never OFF. mmWave sensor uses occupancy class.
  domain: automation
  input:
    light_target:
      name: Lights
      selector:
        target:
          entity:
            domain: light
    office_motion:
      name: Office Motion Sensor (PIR)
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    node_occupancy:
      name: mmWave Node Occupancy Sensor
      description: The mmWave radar sensor (usually device_class = occupancy)
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
    presence_sensor:
      name: Presence / Occupancy Sensor (most accurate)
      description: Usually the same mmWave entity or a separate occupancy entity
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
    door_sensor:
      name: Office Door Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: opening
    motion_on_delay:
      name: Lights-on time when only motion (no presence)
      description: Time to keep lights on if presence was never detected
      default: "00:05:00"
      selector:
        time:
    no_presence_delay:
      name: Lights-off delay after no presence
      description: Time to wait after presence goes OFF before turning lights off
      default: "00:02:00"
      selector:
        time:
    no_presence_timer:
      name: Timer Helper
      description: Create a Timer helper first (no duration needed)
      selector:
        entity:
          domain: timer

trigger:
  - platform: state
    entity_id: !input office_motion
    from: "off"
    to: "on"
    id: pir_motion
  - platform: state
    entity_id: !input node_occupancy
    from: "off"
    to: "on"
    id: mmwave_motion
  - platform: state
    entity_id: !input door_sensor
    from: "off"
    to: "on"
    id: door_open
  - platform: state
    entity_id: !input presence_sensor
    to: "on"
    id: presence_on
  - platform: state
    entity_id: !input presence_sensor
    to: "off"
    id: presence_off
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: !input no_presence_timer
    id: timer_done

mode: restart
max_exceeded: silent

action:
  - choose:
      # Any motion or door opening → turn lights on (only if currently off)
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: pir_motion
              - condition: trigger
                id: mmwave_motion
              - condition: trigger
                id: door_open
        sequence:
          - if:
              - condition: template
                value_template: >-
                  {{ expand(!input light_target) | selectattr('state','eq','off') | list | count > 0 }}
            then:
              - service: light.turn_on
                target: !input light_target
              # If presence is NOT active right now, start the short motion timer
              - if:
                  - condition: state
                    entity_id: !input presence_sensor
                    state: "off"
                then:
                  - service: timer.start
                    data:
                      duration: !input motion_on_delay
                    target:
                      entity_id: !input no_presence_timer

      # Presence detected → turn on lights and cancel any running timer
      - conditions: "{{ trigger.id == 'presence_on' }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
          - service: timer.cancel
            target:
              entity_id: !input no_presence_timer

      # Presence gone → start the longer no-presence timer
      - conditions: "{{ trigger.id == 'presence_off' }}"
        sequence:
          - service: timer.start
            data:
              duration: !input no_presence_delay
            target:
              entity_id: !input no_presence_timer

      # Timer finished → lights off
      - conditions: "{{ trigger.id == 'timer_done' }}"
        sequence:
          - service: light.turn_off
            target: !input light_target
