blueprint:
  name: Alternating Scenes Looper
  description: |
    Creates a script to continuously alternate between two scenes using a loop.
    - Checks if toggle is ON at each cycle start.
    - Applies scene_one, dwells, applies scene_two, dwells, repeats.
    - Stops when toggle is turned OFF (after current dwell).
    Call the script to start the loop (requires toggle ON).
  domain: script
  input:
    scene_one:
      name: First Scene
      description: Starting/alternate scene (e.g., scene.living_room_bright).
      selector:
        entity:
          domain: scene
    scene_two:
      name: Second Scene
      description: Alternate scene (e.g., scene.living_room_dim).
      selector:
        entity:
          domain: scene
    transition_duration:
      name: Transition Duration (seconds)
      description: Time for scene transitions (e.g., 2 for smooth fade).
      default: 1
      selector:
        number:
          min: 0.1
          max: 30
          step: 0.1
          unit_of_measurement: seconds
    dwell_time:
      name: Dwell Time (seconds)
      description: Hold each scene before switching (e.g., 300 for 5 minutes).
      default: 300
      selector:
        number:
          min: 1
          max: 3600
          step: 1
          unit_of_measurement: seconds
    running_toggle:
      name: Running Toggle
      description: Input_boolean; must be ON to loop (turn OFF to stop).
      default: input_boolean.sceen_loop
      selector:
        entity:
          domain: input_boolean

sequence:
  # Infinite loop while toggle is ON
  - repeat:
      while:
        - condition: state
          entity_id: !input running_toggle
          state: 'on'
      sequence:
        # Apply scene one
        - service: scene.turn_on
          target:
            entity_id: !input scene_one
          data:
            transition: !input transition_duration
        - delay:
            seconds: !input dwell_time
        # Apply scene two
        - service: scene.turn_on
          target:
            entity_id: !input scene_two
          data:
            transition: !input transition_duration
        - delay:
            seconds: !input dwell_time

mode: single  # Queues if called while running; change to 'restart' to interrupt
